name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
      - feature/book

  # disable branches to avoid  https://github.com/Azure/static-web-apps/issues/765
  # # reenable once fixed in azure
  # pull_request:
  #   types: [opened, synchronize, reopened, closed]
  #   branches:
  #     - master

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install system dependencies
        run: |
          sudo apt-get -qq update
          sudo apt-get install -y gdal-bin libgdal-dev
          # check version that is installed for python compatibility
          gdalinfo --version
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
          cache: "pip"
      - name: Install Python dependencies
        run: |
          # Install old version of pip /setuptools, issue with gdal. I still get this issue...
          python -m pip install --upgrade pip setuptools==57.5
          # install gdal separate
          pip install wheel==0.38.4 gdal==3.4.1
          # Now upgrade pip / setuptools for real
          python -m pip install --upgrade pip setuptools
          # now install the rest
          pip install -e .[testing]
      - name: Copy examples and build the book
        run: |
          ls -alh
          pwd
          ./build_book.sh
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DELIGHTFUL_CLIFF_0E49C3503 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/book" # App source code path
          api_location: "/api" # Api source code path - optional
          output_location: "_build/html" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DELIGHTFUL_CLIFF_0E49C3503 }}
          action: "close"
